dist: trusty

sudo: required

services:
  - docker

language: generic

notifications:
  email:
    on_failure: never
    on_success: never

env:
  global:
  - CHANGE_MINIKUBE_NONE_USER=true
  - KUBERNETES_VERSION=v1.10.0
  - DOCKER=docker

before_script:
- test/e2e/up.sh
- SKIP_MINIKUBE_START=true make dev-env
script:
- FOCUS=external make e2e-test
